---
## Install Docker CE
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - lsb-release
      - conntrack
    state: present
    update_cache: yes

- name: Install Docker-CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: vagrant user in docker group
  user:
    name: vagrant
    groups: docker

## Set sysctl
- name: Set sysctl
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes
- name: Set sysctl
  sysctl:
    name: fs.protected_regular
    value: "0"
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes

