---
- hosts: vagrants
  become: true
  user: vagrant
  gather_facts: yes
  roles:
    - role: gantsign.keyboard
      keyboard_model: pc105
      keyboard_layout: jp
  tasks:
    - import_tasks: ./tasks/localization.yml
      tags:
        - japan
    - import_tasks: ./tasks/install_misc.yml
      tags:
        - tools
    - import_tasks: ./tasks/ubuntu-desktop.yml
      tags:
        - gui
